### ISSUE TITLE
Gradle import

### ISSUE THREAD

**Issue by fedex995** [naman14/TAndroidLame#1]
Hi,
I'm trying to import this project, but when I add the dependency to my grade file, it says that it can't resolve this dependency.
Thank you

**Comment by naman14** [comment]
Hmm, build is failing at jitpack. I have reported the issue here - https://github.com/jitpack/jitpack.io/issues/438

Till then, please add library as a module

**Comment by tehmaestro** [comment]
Hi, great job on the plugin but unfortunately I cannot use it. I cannot use the experimental plugin in my project, at this point.
  So is there any other way to install the plugin? Using jitpack fails, it cannot resolve the dependency. Thank you.

**Comment by naman14** [comment]
Hmm, I will generate an aar which you can directly include in your project. Will share it by tomorrow

**Comment by tehmaestro** [comment]
Thank you, sorry, I'm not used to including stuff in an Android project. I actually use Cordova and Crosswalk to build a hybrid web application for android, I'm just getting started with native Android code. 

The project was built using the cordova cli https://cordova.apache.org/docs/en/4.0.0/guide/cli/ . This generates a gradle project, which I imported in Android Studio.

**Comment by geogie** [comment]
How can I use aar to My Project??

**Comment by geogie** [comment]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not resolve com.github.naman14:TAndroidLame:1.0.
  >  Required by:
  >      TestAndroids:app:unspecified
  > Could not resolve com.github.naman14:TAndroidLame:1.0.
  >      > Could not get resource 'https://jcenter.bintray.com/com/github/naman14/TAndroidLame/1.0/TAndroidLame-1.0.pom'.
  >         > Could not GET 'https://jcenter.bintray.com/com/github/naman14/TAndroidLame/1.0/TAndroidLame-1.0.pom'.
  >            > peer not authenticated
  > Could not resolve com.github.naman14:TAndroidLame:1.0.
  >      > Could not get resource 'https://jitpack.io/com/github/naman14/TAndroidLame/1.0/TAndroidLame-1.0.pom'.
  >         > Could not GET 'https://jitpack.io/com/github/naman14/TAndroidLame/1.0/TAndroidLame-1.0.pom'.
  >            > The target server failed to respond
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6 mins 35.073 secs

**Comment by huange3** [comment]
@naman14 Hello, did you ever share the aar file? I'm still encountering build errors. Would really appreciate an aar!

**Comment by hyd00** [comment]
@naman14  bro really appreciate if you can share AAR file ???

**Comment by naman14** [comment]
Building using gradle dependency from Jitpack should be fixed now. (Use the 1.1 release, see readme)

```gradle
apply plugin: 'com.github.dcendents.android-maven' //add it to top of app level build.gradle  

dependencies {
	        compile 'com.github.naman14:TAndroidLame:1.1'
	}
```
