### ISSUE TITLE
Does is support x86?

### ISSUE THREAD

**Issue by aratn0n** [naman14/TAndroidLame#11]
I saw the lib file is only for armeabi. Is there anyway that I can build it to support x86 as well?

**Comment by moti0375** [comment]
Hi,

You should run the ndk-build as explained in the README instructions, this will generate the rest include support for x86

From the README:
"Use ndk-build in androidlame/src/main/jni (where Android.mk is located) to generate the libandroidlame.so shared library
(Android studio should automatically generate the so file when building but somehow it doesn't)"
