### ISSUE TITLE
no file?

### ISSUE THREAD

**Issue by geogie** [naman14/TAndroidLame#3]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not find com.github.naman14:TAndroidlame:1.0.
  >  Searched in the following locations:
  >      https://jcenter.bintray.com/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.pom
  >      https://jcenter.bintray.com/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.jar
  >      https://jitpack.io/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.pom
  >      https://jitpack.io/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.jar
  >      file:/D:/Users/Administrator/AppData/Local/Android/sdk/extras/android/m2repository/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.pom
  >      file:/D:/Users/Administrator/AppData/Local/Android/sdk/extras/android/m2repository/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.jar
  >      file:/D:/Users/Administrator/AppData/Local/Android/sdk/extras/google/m2repository/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.pom
  >      file:/D:/Users/Administrator/AppData/Local/Android/sdk/extras/google/m2repository/com/github/naman14/TAndroidlame/1.0/TAndroidlame-1.0.jar
  >  Required by:
  >      AndroidText2:app:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by naman14** [comment]
Building using gradle dependency from Jitpack should be fixed now. (Use the 1.1 release, see readme)

```gradle
apply plugin: 'com.github.dcendents.android-maven' //add it to top of app level build.gradle  

dependencies {
	        compile 'com.github.naman14:TAndroidLame:1.1'
	}
```
