### ISSUE TITLE
Cant Compile it 

### ISSUE THREAD

**Issue by sanaullah1234** [naman14/TAndroidLame#6]
Please help to compile . i cant compile it as a module and through github url as well.

**Comment by naman14** [comment]
Building using gradle dependency from Jitpack should be fixed now. (Use the 1.1 release, see readme)

```gradle
apply plugin: 'com.github.dcendents.android-maven' //add it to top of app level build.gradle  

dependencies {
	        compile 'com.github.naman14:TAndroidLame:1.1'
	}
```
